version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=${MONGO_URI}  # Charge l'URL MongoDB depuis le fichier .env
      - PORT=${PORT}             # Charge le port depuis .env
    volumes:
      - ./server:/app  # Monte le dossier local dans le conteneur pour le Hot Reload
      - /app/node_modules  # Ignore les node_modules pour éviter les conflits
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"